Add Airplane Minecraft server jar
parkervcp/eggs pull request #1266
Opened 2021-07-24 21:43 UTC by TTRCharlie

### All Submissions:

* [X] Have you followed the guidelines in our Contributing document?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [X] Did you branch your changes and PR from that branch and not from your master branch?

### New Server Submissions:

1. [X] Does your submission pass tests (server is connectable)?
2. [X] Have you added the server to the main README.md?

### Changes to an existing Egg:

1. [X] Have you tested your Egg changes?

2021-07-25 03:07 UTC, Software-Noob requested changes

2021-07-25 03:07 UTC, Software-Noob commented on game_eggs/minecraft/java/airplane/egg-airplane.json
> +            "description": "Here you can set which build version you want to use from Airplane release",
Would you please provide a URL from where users can find the build version `https://ci.tivy.ca`

2021-07-25 10:26 UTC, TTRCharlie commented
I already corrected the lines were you showed

2021-07-27 15:05 UTC, Software-Noob approved these changes
LGTM, thank you for the contribution!

2021-07-27 15:05 UTC, merged