update sogeBot - see changelog
parkervcp/eggs pull request #1449
Opened 2021-12-08 06:44 UTC by gOOvER

### All Submissions:

* [ ] Have you followed the guidelines in our Contributing document?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [ ] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

### Changes to an existing Egg:

1. [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
2. [ ] Have you tested your Egg changes?

### Changelog

- add database backup on reinstall
- add more folder cleanup to prevent errors on update
- fixed missing dotenv module

The egg need the PR https://github.com/parkervcp/yolks/pull/29, because buster have a too old sqllite version and throws missing sqlite errors.

2021-12-13 01:07 UTC, Software-Noob requested changes

2021-12-13 01:07 UTC, Software-Noob commented on bots/twitch/sogebot/egg-soge-bot.json
> +        "stop": "^C"
^^C is a current workaround regarding catching termination signals when using eval for startup parsing. ^C doesn't get passed, and the server will be stuck stopping until Pterodactyl kills it

2021-12-13 01:07 UTC, Software-Noob commented on bots/twitch/sogebot/egg-soge-bot.json
> +            "script": "#\/bin\/bash\r\n# Installscript for sogeBot | Author: info@goover.de\r\n\r\nexport DEBIAN_FRONTEND=noninteractive\r\n\r\napt -y update\r\napt install -y curl unzip sqlite3 jq w
`no errors` should be `not errors`

2021-12-13 14:17 UTC, gOOvER commented on bots/twitch/sogebot/egg-soge-bot.json
> +        "logs": "{\r\n    \"custom\": false,\r\n    \"location\": \"logs\/latest.log\"\r\n}",
fixed

2021-12-13 14:18 UTC, gOOvER commented on bots/twitch/sogebot/egg-soge-bot.json
> +            "script": "#\/bin\/bash\r\n# Installscript for sogeBot | Author: info@goover.de\r\n\r\nexport DEBIAN_FRONTEND=noninteractive\r\n\r\napt -y update\r\napt install -y curl unzip sqlite3 jq w
fixed

2021-12-14 16:13 UTC, Software-Noob approved these changes
LGTM, thank you for contributing :+1:

2021-12-14 16:15 UTC, merged