Add Left 4 Dead and Left 4 Dead 2
parkervcp/eggs pull request #1487
Opened 2021-12-18 16:42 UTC by gmazoyer

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Did you branch your changes and PR from that branch and not from your master branch?

### New Server Submissions:

1. [x] Does your submission pass tests (server is connectable)?
2. [ ] Does your server use a custom docker image?
    * [ ] Have you tried to use a generic image?
    * [ ] Did you PR the necessary changes to make it work?
3. [x] Have you added the server to the main README.md?
4. [x] Have you added a unique README.md for the server you are adding?

2021-12-18 17:11 UTC, gOOvER requested changes

2021-12-18 17:11 UTC, gOOvER commented on game_eggs/steamcmd_servers/left4dead/egg-left4dead.json
> +        "quay.io\/pterodactyl\/core:source"
pls use new yolks image:
ghcr.io/parkervcp/games:source

2021-12-18 17:11 UTC, gOOvER commented on game_eggs/steamcmd_servers/left4dead/egg-left4dead.json
> +            "container": "debian:bullseye",
pls use the yolks installer

ghcr.io/pterodactyl/installers:debian

2021-12-18 17:11 UTC, gOOvER commented on game_eggs/steamcmd_servers/left4dead_2/egg-left4dead_2.json
> +        "quay.io\/pterodactyl\/core:source"
same her: 

ghcr.io/parkervcp/games:source

2021-12-18 17:11 UTC, gOOvER commented on game_eggs/steamcmd_servers/left4dead_2/egg-left4dead_2.json
> +            "container": "debian:bullseye",
also use the yolks installer:
ghcr.io/pterodactyl/installers:debian

2021-12-18 17:12 UTC, gOOvER requested changes
Please update to new Yolks as mentoined in the comments

2021-12-18 18:03 UTC, gmazoyer commented
Updated with the mentioned images. Re-tested the servers and they still work as expected.

2022-01-09 17:07 UTC, parkervcp commented
the steamcmd generic egg probably could have done this. I am not against it. I am just calling it out.

2022-01-11 09:25 UTC, gmazoyer commented
Indeed you are right. It's simple enough to setup with the generic egg. Feel free to close this MR.

2022-01-11 18:24 UTC, parkervcp approved these changes

2022-01-11 18:24 UTC, merged