Add ServerJars Minecraft Auto-Updater
parkervcp/eggs pull request #1493
Opened 2021-12-22 03:39 UTC by cixastra

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Did you branch your changes and PR from that branch and not from your master branch?

### New Server Submissions:

1. [x] Does your submission pass tests (server is connectable)?
2. [ ] Does your server use a custom docker image?
   No, Server uses default Java Images (8,11,16, & 17)
3. [x] Have you added the server to the main README.md?
4. [x] Have you added a unique README.md for the server you are adding?

2022-01-27 23:31 UTC, cixastra commented
bump^

2022-02-05 13:23 UTC, gOOvER requested changes
you missed to add it to Main Readmin in root

2022-02-06 00:32 UTC, cixastra commented
The main readme has been changed? I don't quite understand what you mean.
<img width="1438" alt="Screen Shot 2022-02-05 at 6 32 28 PM" src="https://user-images.githubusercontent.com/68437385/152663540-d82f29d6-2123-49a8-b150-3e8fe74bbf87.png">

2022-02-19 13:00 UTC, parkervcp requested changes

2022-02-19 13:00 UTC, parkervcp commented on README.md
> +  * [ServerJars AutoUpdater](game_eggs/minecraft/java/ServerJars)
This should be alphabetical

2022-03-12 17:52 UTC, Software-Noob commented
Hard-coding a specific version is a bad idea. Otherwise, this egg itself works fine, but I'm not a big fan of the idea itself.

2022-03-13 20:20 UTC, cixastra commented
I understand the hesitation for using 3.0.0 as a hard coded version, however, traversing GitHub releases in ash is (1) difficult, and (2) not *really* necessary considering the software updates *very* slowly. It has been at 3.0.0 for a very long time now. As it works, Is this pr approved?

2022-03-13 20:29 UTC, Software-Noob commented
> I understand the hesitation for using 3.0.0 as a hard coded version, however, traversing GitHub releases in ash is (1) difficult, and (2) not _really_ necessary considering the software updates _very_ slowly. It has been at 3.0.0 for a very long time now. As it works, Is this pr approved?

That's not a great philosophy when it comes back to bite us back in the ass. I'm against hard-coding specific releases. It's a very bad practice. We do have a [Github release grabber script.](https://github.com/parkervcp/eggs/blob/master/scripts/github_release_grabber.sh)

2022-03-13 20:47 UTC, cixastra commented
I've implimented the release grabber, the script now grabs the latest jarfile. Test for success is complete and reveals no error.

2022-03-19 16:31 UTC, Software-Noob requested changes

2022-03-19 16:31 UTC, Software-Noob commented on game_eggs/minecraft/java/ServerJars/egg-server-jars.json
> +    "startup": "java -Xms{{SERVER_MEMORY}}M -Xmx{{SERVER_MEMORY}}M -Dterminal.jline=false -Dterminal.ansi=true -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimenta
Please keep the flags to a minimum. Most users have no idea what each one of them does in detail, which can cause issues when the server is behaving in unexpected ways regarding garbage collection or memory allocation.

2022-03-19 16:31 UTC, Software-Noob commented on game_eggs/minecraft/java/ServerJars/egg-server-jars.json
> +            "script": "cd \/mnt\/server\r\n\r\ncurl -L -o server.jar https:\/\/github.com\/ServerJars\/updater\/releases\/download\/v3.0.0\/ServerJars-3.jar\r\n\r\nGITHUB_PACKAGE=\"ServerJars\/Update
You copied the Github release grabber, but there is no  `VERSION` variable.

There should be an echo of some kind at the end to provide feedback when the installation is completed. Right now, there's nothing that might confuse someone.

2022-05-17 17:38 UTC, closed without merging