Modified Factorio Egg for better start script
parkervcp/eggs pull request #1513
Opened 2022-01-02 20:24 UTC by IConnC

Originally, the startup script for the Factorio egg would fail if the save file was missing, this PR fixes that by running the save generator prior to server start if the save file does not already exist.

### All Submissions:

* [X] Have you followed the guidelines in our Contributing document?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [X] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

### Changes to an existing Egg:

1. [X] Have you added an explanation of what your changes do and why you'd like us to include them?
2. [X] Have you tested your Egg changes?

2022-01-02 21:08 UTC, gOOvER requested changes
quay is outdated. You should add the new yolk images

2022-01-02 21:08 UTC, gOOvER commented on game_eggs/factorio/factorio/egg-factorio.json
> +        "quay.io\/parkervcp\/pterodactyl-images:base_debian"
Pls use the new yolks

2022-01-02 21:08 UTC, gOOvER commented on game_eggs/factorio/factorio/egg-factorio.json
>              "container": "debian:buster-slim",
as here: pls use the new yolks

2022-01-03 03:48 UTC, IConnC commented
Updated to ghcr.io repository

2022-01-03 09:24 UTC, gOOvER approved these changes
for me it works. Server was installed and i can connect

2022-01-09 17:03 UTC, parkervcp approved these changes

2022-01-09 17:03 UTC, merged