Add Loki egg
parkervcp/eggs pull request #1606
Opened 2022-04-06 21:09 UTC by realkarmakun

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Did you branch your changes and PR from that branch and not from your master branch?

### New Server Submissions:

1. [x] Does your submission pass tests (server is connectable)?
3. [x] Have you added the server to the main README.md?
4. [x] Have you added a unique README.md for the server you are adding?

2022-04-13 06:09 UTC, DatMayo commented
You can add "closes #1590" to your PR, so it will be automaticly closed when your PR is merged :)

2022-04-18 22:09 UTC, realkarmakun commented
> You can add "closes #1590" to your PR, so it will be automaticly closed when your PR is merged :)

I'm sorry, where should I do that exactly? Right here in the comments? Or in commit message? I don't quite understand what you want..

2022-04-18 22:09 UTC, realkarmakun commented
closes https://github.com/parkervcp/eggs/issues/1590

2022-05-16 12:32 UTC, realkarmakun commented
This closes https://github.com/parkervcp/eggs/issues/1590

2022-05-16 12:35 UTC, realkarmakun commented
@DatMayo Is this what you wanted? To change the PR's name?

2022-05-21 15:43 UTC, Software-Noob requested changes

2022-06-06 20:47 UTC, realkarmakun commented on monitoring/loki/egg-loki.json
> +        "quay.io\/parkervcp\/pterodactyl-images:base_debian"
Done in https://github.com/parkervcp/eggs/pull/1606/commits/33a72c0069d503047d57a30d61d74d6b2114987a

2022-06-06 20:48 UTC, realkarmakun reviewed
Using new yolk repo now https://github.com/parkervcp/eggs/pull/1606/commits/33a72c0069d503047d57a30d61d74d6b2114987a

2022-07-03 21:51 UTC, Software-Noob approved these changes
LGTM. Thank you for contributing :+1:

I've cleaned it up a tad and fixed the readme.  Using an existing install image that contains the necessary packages speeds up the installation. Globbing is already enabled in Debian, and creating a new variable just to assign an existing variable value to it is unnecessary. 

Preferably we always echo what we're doing, so it's easier to troubleshoot once users report issues. I've added an echo of the curl URL in use.

2022-07-03 21:51 UTC, merged