Update Among Us - Impostor
parkervcp/eggs pull request #1721
Opened 2022-06-22 14:20 UTC by JackW6809

The .NET Image used here is out of date and it requires .NET 6 to run. They have their own image so I have instead switched the image to that and the issue has been resolved.

> I'd rather you update the image versus updating the egg to use your image. #1261

I am not sure how you want us to update the image if this is hosted on your side and when I tried to use the following image it does not exist -```quay.io\/parkervcp\/pterodactyl-images:debian_dotnet-6```
Whereas the image I have provided, like the one in the previously mentioned PR, is the one provided by the developers of Impostor. This can be found here and using this image does not lead to any issues - https://github.com/Impostor/Impostor/blob/master/docs/Running-the-server.md#using-docker-compose

### All Submissions:

* [X] Have you followed the guidelines in our Contributing document?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [X] Did you branch your changes and PR from that branch and not from your master branch?

### Changes to an existing Egg:

1. [X] Have you added an explanation of what your changes do and why you'd like us to include them?
2. [X] Have you tested your Egg changes?

2022-06-22 14:23 UTC, parkervcp requested changes

2022-06-22 14:23 UTC, parkervcp commented on game_eggs/among_us/impostor_server/egg-among-us--impostor-server.json
> +        "qaeonlucid/impostor:nightly"
If my image is out of date please PR to update that instead of using your own image.

2022-06-22 14:24 UTC, parkervcp commented on game_eggs/among_us/impostor_server/egg-among-us--impostor-server.json
> +        "qaeonlucid/impostor:nightly"
I do have this image `ghcr.io/parkervcp/yolks:dotnet_6`

2022-06-22 14:35 UTC, JackW6809 commented
Resolved and now using your .NET image as requested.

2022-06-22 15:14 UTC, Software-Noob approved these changes
LGTM. Thank you for contributing :+1:

2022-06-28 01:38 UTC, parkervcp approved these changes

2022-06-28 01:38 UTC, merged