Create egg-vanilla-bedrock-ARM64.json
parkervcp/eggs pull request #1743
Opened 2022-07-06 15:17 UTC by QuintenQVD0

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Did you branch your changes and PR from that branch and not from your master branch?

### New Server Submissions:

1. [] Does your submission pass tests (server is connectable)?
Still need to test
2. [x] Does your server use a custom docker image?
    * [x] Have you tried to use a generic image?
    * [x] Did you PR the necessary changes to make it work?
    https://github.com/parkervcp/yolks/pull/63
3. [x] Have you added the server to the main README.md?
4. [x] Have you added a unique README.md for the server you are adding?

2022-07-08 14:05 UTC, kry008 approved these changes
Working and allow stable play

2022-07-19 16:17 UTC, parkervcp approved these changes

2022-07-19 16:18 UTC, parkervcp requested changes
Can you update the README for bedrock to make note that the arm64 may not perform as expected due to the amd64 to arm emulaton.

2022-07-19 16:29 UTC, QuintenQVD0 commented
> Can you update the README for bedrock to make note that the arm64 may not perform as expected due to the amd64 to arm emulaton.

Done

2022-07-22 15:43 UTC, parkervcp approved these changes

2022-07-22 16:32 UTC, merged