Move Generic Language Eggs
parkervcp/eggs pull request #1774
Opened 2022-07-25 18:25 UTC by parkervcp

This moves all the generic language eggs into a separate folder

No changes to the eggs except for their names and removing anything pertaining to bots. This excludes the python egg where a bot repo was used for testing.

### All Submissions:
* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

### Changes to an existing Egg:
1. [x] Have you added an explanation of what your changes do and why you'd like us to include them?
2. [ ] Have you tested your Egg changes?

2022-08-14 11:27 UTC, Software-Noob commented
Nodemon egg is a generic too for nodejs apps, move it as well?

The readme of java, node, and go eggs have their old discord-{lang} name titles. That's probably something that should be changed as well to prevent confusion.

The main readme file must also be modified to remove the old discord folder path and display a new generic one. The discord folder readme must be modified to remove the non-existing discord eggs.

The generic folder by itself is not very descriptive to end users. Maybe `generic-code`?

Otherwise, LGTM

2022-09-18 06:04 UTC, gOOvER commented on generic/golang/egg-golang-generic.json
> +        "quay.io\/parkervcp\/pterodactyl-images:base_debian": "quay.io\/parkervcp\/pterodactyl-images:base_debian"
This should be a ghcr image

2022-09-18 06:05 UTC, gOOvER requested changes

2022-09-18 06:05 UTC, gOOvER commented on generic/golang/egg-golang-generic.json
> +        "quay.io\/parkervcp\/pterodactyl-images:base_debian": "quay.io\/parkervcp\/pterodactyl-images:base_debian"
This should be a ghcr image

2022-09-23 17:03 UTC, QuintenQVD0 approved these changes
Looks good to me!

2022-09-23 17:03 UTC, merged