add Solace Crafting
parkervcp/eggs pull request #1927
Opened 2022-10-23 12:09 UTC by gOOvER

# Description

Add egg for Solace Crafting. STEAM AUTH NEEDED
Fixes #1893 

## Checklist for all submissions

* [ ] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [ ] Have you tested and reviewed your changes with confidence that everything works?
* [ ] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

## New egg Submissions

1. [ ] Does your submission pass tests (server is connectable)?
2. [ ] Does your egg use a custom docker image?
    * [ ] Have you tried to use a generic image?
    * [ ] Did you PR the necessary changes to make it work?
3. [ ] Have you added the egg to the main README.md and any other README files in subdirectories of the egg (e.g /game_eggs) according to the alphabetical order?
4. [ ] Have you added a unique README.md for the egg you are adding according to the alphabetical order?

2022-10-24 17:54 UTC, BrickBotTM requested changes
The app id should be 1086950 so it can be logging in as anonymous for install. 1086950 is for the normal dedicated server. That way you don't need someone who owns the game to install the server. So you don't need the variables.

2022-10-24 18:00 UTC, gOOvER commented
> The app id should be 1086950 so it can be logging in as anonymous for install. 1086950 is for the normal dedicated server. That way you don't need someone who owns the game to install the server. So you don't need the variables.

both appids are the same. The dev never switched to anonymous login ;) Read the discord; i asked now 1000 times and the dev told me 1000 times he changed it

2022-10-24 18:12 UTC, gOOvER commented
> The app id should be 1086950 so it can be logging in as anonymous for install. 1086950 is for the normal dedicated server. That way you don't need someone who owns the game to install the server. So you don't need the variables.

ty for the tip. The dev was not able to give me this info. I ixx the egg AppId

2022-10-24 18:13 UTC, gOOvER commented
Updated egg and remove the complete login

2022-10-25 02:13 UTC, BrickBotTM approved these changes
Works like a charm now!

2022-10-25 05:06 UTC, QuintenQVD0 requested changes

2022-10-25 05:06 UTC, QuintenQVD0 commented on game_eggs/steamcmd_servers/solace_crafting/README.md
> +To start this Server, Steam Login is needed
So this is then not more needed in the readme ?

2022-10-25 15:10 UTC, QuintenQVD0 approved these changes

2022-10-25 15:10 UTC, merged