Update Stormworks
parkervcp/eggs pull request #1933
Opened 2022-10-26 17:53 UTC by delphyinium

# Description
This is a fix that was tested in the issue mentioned #1851 

Changes:

- change image from wine_latest to wine_staging
- update readme to address console output and tps misreporting
closes https://github.com/parkervcp/eggs/issues/1851

## Checklist for all submissions

* [X] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [X] Have you tested and reviewed your changes with confidence that everything works?
* [X] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

2022-10-26 17:58 UTC, QuintenQVD0 requested changes
Use the panel export feature. You dont edit the json file directly. Then the egg will update to pltv_2 format if your panel is up to date

2022-10-26 18:16 UTC, delphyinium commented
> Use the panel export feature. You dont edit the json file directly. Then the egg will update to pltv_2 format if your panel is up to date

Apologies. Fixed. I went through the effort of deleting the file and uploading the new one when I could have just edited the existing file 🤦 
Should be good now though.

2022-10-26 19:38 UTC, QuintenQVD0 commented
This egg needs a extra variable to auto update steamcmd. And in the install script can be upate as the apt update and the apt install is not needed because it uses the install image that has all those packages

2022-10-26 20:59 UTC, delphyinium commented
> This egg needs a extra variable to auto update steamcmd. And in the install script can be upate as the apt update and the apt install is not needed because it uses the install image that has all those packages. And the new echo done at the end of install script. If you don't want to do that I will do that for you tommorow.

I believe I have fixed everything. I tested Auto-Update to verify it checks for an update, which it does. I also got rid of the apt install, since it is not required like you said, and added an echo at the end to signal it has completed installation.

2022-10-27 05:10 UTC, QuintenQVD0 requested changes

2022-10-27 05:10 UTC, QuintenQVD0 commented on game_eggs/steamcmd_servers/stormworks/egg-stormworks--build-and-rescue.json
> +            "rules": "required|string|max:20",
This should be `required|boolean`

2022-10-27 05:11 UTC, QuintenQVD0 requested changes

2022-10-27 05:11 UTC, QuintenQVD0 commented on game_eggs/steamcmd_servers/stormworks/egg-stormworks--build-and-rescue.json
> +        "ghcr.io\/parkervcp\/yolks:wine_staging": "ghcr.io\/parkervcp\/yolks:wine_staging"
Please use `Wine_staging|<url>` in the panel docker image so then it when it export it only shows wine staging to the end user.

2022-10-27 05:13 UTC, QuintenQVD0 commented
If the eggs then can be tested by someone or I will do it in the weekend then I will aprove this.

2022-10-27 12:10 UTC, delphyinium commented
> If the eggs then can be tested by someone or I will do it in the weekend then I will aprove this. 

Ok, I can fix these in a bit, then I'll test and get back to you.

2022-10-28 02:08 UTC, delphyinium commented
Sorry for the delay, I quickly made the changes you requested. I tested and it seems to be running smooth. Once again apologies for the delay.

2022-10-28 04:55 UTC, QuintenQVD0 approved these changes

2022-10-28 04:56 UTC, QuintenQVD0 commented
Np, LGTM!

2022-10-28 04:56 UTC, merged