Added a space to avoid additional args breaking the app port.
parkervcp/eggs pull request #1944
Opened 2022-11-01 03:53 UTC by pedrotski

# Description

Adding an additional argument would break the app port as it would be added like this

Example: 

+app.port 28083-logfile

 +app.port 28083 -logfile

adding the space fixes that.

## Checklist for all submissions

* [X] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [X] Have you tested and reviewed your changes with confidence that everything works?
* [X] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

2022-11-01 07:18 UTC, QuintenQVD0 requested changes
Dont just edit the json file. Edit it in the panel and export it.

2022-11-01 08:05 UTC, lilkingjr1 commented
> Dont just edit the json file. Edit it in the panel and export it.

May I ask why? They just added a single, needed, space character; properly too. Looks fine to me (assuming it's the only thing that needs changing).

2022-11-01 08:07 UTC, QuintenQVD0 commented
> > Dont just edit the json file. Edit it in the panel and export it.
> 
> May I ask why? They just added a single, needed, space character; properly too. Looks fine to me (assuming it's the only thing that needs changing).

Then the egg goos to pltv_2 format (if your panel is up to date) and then match the export date the date of this PR

2022-11-01 08:11 UTC, lilkingjr1 commented
> > > Dont just edit the json file. Edit it in the panel and export it.
> > 
> > 
> > May I ask why? They just added a single, needed, space character; properly too. Looks fine to me (assuming it's the only thing that needs changing).
> 
> Then the egg goos to pltv_2 format (if your panel is up to date) and then match the export date the date of this PR

Ahh, didn't notice the egg was still PTDL_v1. Makes sense.

2022-11-01 10:07 UTC, pedrotski commented
Totally replaced it to the new version. Turns out the stock eggs here are outdated.

2022-11-01 10:17 UTC, Software-Noob commented
The stock eggs are not to be up to date with the upstream as mentioned in the readme. That's not what they are meant for.

Honestly they should be removed all together due to constant confusion and only leave readme with a link to upstream. Any PRs to upstream can be done through branches.

2022-11-01 11:36 UTC, QuintenQVD0 commented
> The stock eggs are not to be up to date with the upstream as mentioned in the readme. That's not what they are meant for.
> 
> Honestly they should be removed all together due to constant confusion and only leave readme with a link to upstream. Any PRs to upstream can be done through branches.

I will have a look later this day to just remove the stock eggs here and 1 readme that points to the eggs in the panel repo

2022-11-01 12:44 UTC, QuintenQVD0 commented
if this https://github.com/parkervcp/eggs/pull/1945 get merged then this pr is not more needed. But keep it open for now

2022-11-02 00:25 UTC, parkervcp requested changes

2022-11-02 00:25 UTC, parkervcp commented on stock_eggs/rust/egg-rust.json
> +            "env_variable": "MAP_URL",
You added more than just a space.

2022-11-02 00:25 UTC, parkervcp commented
Actually if this is a stock egg make the PR there.

2022-11-02 00:25 UTC, closed without merging