Add LiteLoaderBDS egg
parkervcp/eggs pull request #1992
Opened 2022-12-06 15:29 UTC by Lycol50

# Description

Creation of LiteLoaderBDS egg support

## Checklist for all submissions

* [X] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [X] Have you tested and reviewed your changes with confidence that everything works?
* [X] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

## New egg Submissions

1. [X] Does your submission pass tests (server is connectable)?
2. [ ] Does your egg use a custom docker image?
    * [X] Have you tried to use a generic image?
    * [ ] Did you PR the necessary changes to make it work?
3. [X] Have you added the egg to the main README.md and any other README files in subdirectories of the egg (e.g /game_eggs) according to the alphabetical order?
4. [X] Have you added a unique README.md for the egg you are adding according to the alphabetical order?

2022-12-06 15:37 UTC, QuintenQVD0 requested changes

2022-12-06 15:37 UTC, QuintenQVD0 commented on game_eggs/minecraft/bedrock/LiteLoader-bedrock/egg-LiteLoader-bedrock.json
> +        "logs": "{\r\n    \"custom\": false,\r\n    \"location\": \"logs/latest.log\"\r\n}",
This not not used anymore

2022-12-06 15:37 UTC, QuintenQVD0 commented on game_eggs/minecraft/bedrock/LiteLoader-bedrock/egg-LiteLoader-bedrock.json
> +            "default_value": "2.8.1",
This by default should be latest

2022-12-06 16:41 UTC, QuintenQVD0 commented
Alos where are your commit to adding it to the main readme and sub readme of game eggs a Minecraft and bedrock

2022-12-06 16:43 UTC, QuintenQVD0 requested changes

2022-12-07 06:08 UTC, Lycol50 commented on game_eggs/minecraft/bedrock/LiteLoader-bedrock/egg-LiteLoader-bedrock.json
> +            "script": "#!\/bin\/bash\r\n# Liteloader First-time Install Script\r\n\r\nrm -r \/mnt\/server\r\nmkdir \/mnt\/server\r\ncd \/mnt\/server\r\nwget https:\/\/minecraft.azureedge.net\/bin-win
acknowledged

2022-12-07 06:08 UTC, Lycol50 commented on game_eggs/minecraft/bedrock/LiteLoader-bedrock/egg-LiteLoader-bedrock.json
> +            "default_value": "1.19.41.01",
acknowledged

2022-12-07 06:08 UTC, Lycol50 commented on game_eggs/minecraft/bedrock/LiteLoader-bedrock/egg-LiteLoader-bedrock.json
> +            "default_value": "2.8.1",
acknowledged

2022-12-07 13:40 UTC, QuintenQVD0 commented
The downloading of the binary's of LiteLoaderBDS should be done with curl and not wget
and the downloading should be done outside the script to get the version so only 1 line is needed to download the binary. Also please use our github script to get the versions

2022-12-07 13:43 UTC, parkervcp commented
> done with curl and not wget

Both are fine as long as they get the files.

2022-12-07 13:44 UTC, QuintenQVD0 commented
wy did you close it? for the rest it looks fine

2022-12-07 13:48 UTC, Lycol50 commented
> wy did you close it? for the rest it looks fine

You didn't review the changes, before you comment.
1. The last commits are now just the same with Bedrock Server Egg, so hence it uses the github script
2. wget and curl are just the same (to get files)

I will not re-open this pull request anymore. Thanks

2022-12-07 14:42 UTC, QuintenQVD0 commented
> > wy did you close it? for the rest it looks fine
> 
> You didn't review the changes, before you comment.
> 
>     1. The last commits are now just the same with Bedrock Server Egg, so hence it uses the github script
> 
>     2. wget and curl are just the same (to get files)
> 
> 
> ~I will not re-open this pull request anymore. Thanks~

Then it looks fine to me. I don't have time ATM but if someone can confirm that it works and can join the server then this will be merged

2022-12-11 11:22 UTC, Lycol50 commented
> I tested the egg and need to changes:
> 
> * Move to wine staging image
> * set the startup done to `IPv4 supported`

may I know why it need to use the wine staging image, instead of wine latest one?

2022-12-11 11:28 UTC, QuintenQVD0 commented
> > I tested the egg and need to changes:
> > 
> > * Move to wine staging image
> > * set the startup done to `IPv4 supported`
> 
> may I know why it need to use the wine staging image, instead of wine latest one?

Wine staging receives way more bug fixes, if anything changes to LiteLoaderBDS  code then likly wine staging will handel it beter as it gets way more updates ( wine is a v 7.0 and staging at 7.22)

2022-12-11 11:29 UTC, QuintenQVD0 commented
also please use the panel export feature as then the exported time changes, we may need this in the future

2022-12-11 11:31 UTC, Lycol50 commented
okay, i understand. This will be noted in the future.

2022-12-11 11:46 UTC, QuintenQVD0 commented
LGTM! Thank you!

2022-12-11 11:47 UTC, merged