update/valheim-vanilla
parkervcp/eggs pull request #1994
Opened 2022-12-08 22:36 UTC by Attackwave

# Description

Added new command line arguments:
- public server y/n (public)
- backup settings (saveinterval, backups, backupshort, backuplong)

## Checklist for all submissions

* [X] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [X] Have you tested and reviewed your changes with confidence that everything works?
* [X] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

2022-12-08 22:40 UTC, Attackwave commented
![image](https://user-images.githubusercontent.com/51136146/206581980-c98a469b-f9b5-40c9-84c0-b99ba1bd8470.png)
![image](https://user-images.githubusercontent.com/51136146/206582213-0663ab65-a457-4dfd-bc02-e0c8a5f85105.png)

2022-12-13 16:45 UTC, parkervcp requested changes

2022-12-13 16:45 UTC, parkervcp commented on game_eggs/steamcmd_servers/valheim/valheim_vanilla/egg-valheim.json
> +            "description": "Change how often the world will save in seconds.",
You want to make a note that this is 30 minutes by default

2022-12-27 11:08 UTC, Attackwave commented
Variables/Descriptions synced and updated.

2023-01-12 18:36 UTC, gOOvER approved these changes
works without problems, as already mentioned in Discord

2023-01-12 18:50 UTC, QuintenQVD0 approved these changes

2023-01-12 18:50 UTC, merged