Fix Don't Starve Together
parkervcp/eggs pull request #2038
Opened 2023-01-03 17:10 UTC by DatCaptainHorse

# Description

**Changes:**
- Switched to using x64 server binaries to allow more RAM to be utilized if needed.
- Remove deprecated and unneeded launch parameters, as configs are already being modified to have correct values.
- Change Caves-shard id to 2, as it's the 2nd shard in the cluster.
- Bind cluster IP to 0.0.0.0 to allow incoming connections to it for proxying.
- Warn about using shard ports in the egg README, using these will prevent either shard from working properly.

Overall these changes fix #2035, with some additional cleanup of the egg.

## Checklist for all submissions

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you tested and reviewed your changes with confidence that everything works?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

2023-01-03 17:40 UTC, QuintenQVD0 approved these changes

2023-01-03 17:40 UTC, QuintenQVD0 commented on game_eggs/steamcmd_servers/dont_starve/egg-don-t-starve-together.json
>          "startup": "{\r\n    \"done\": \"Setting breakpad minidump AppID\",\r\n    \"userInteraction\": []\r\n}",
userInteraction is not more uses

2023-01-03 17:40 UTC, QuintenQVD0 commented on game_eggs/steamcmd_servers/dont_starve/egg-don-t-starve-together.json
>          "quay.io\/parkervcp\/pterodactyl-images:debian_source"
this should be `ghcr.io/parkervcp/steamcmd:debian` but that image is not yet public

2023-01-03 17:41 UTC, QuintenQVD0 commented
also please move the image to
    ghcr.io/parkervcp/steamcmd:debian

2023-01-03 18:07 UTC, parkervcp requested changes

2023-01-03 18:07 UTC, parkervcp commented on game_eggs/steamcmd_servers/dont_starve/egg-don-t-starve-together.json
> -    "startup": "cd bin && coproc caves ( .\/dontstarve_dedicated_server_nullrenderer -console -persistent_storage_root \/home\/container\/DoNotStarveTogether -conf_dir config -cluster server -players
My answer here is going to be a no for most of this as I have it working locally. I need to validate it and get my PR pushed.

2023-01-07 15:49 UTC, parkervcp commented
I am closing this as all that was needed were minor changes to the startup and the image being used

2023-01-07 15:49 UTC, closed without merging