Update Rust and frozen flame
parkervcp/eggs pull request #2113
Opened 2023-02-03 05:55 UTC by Wapriaily

# Description

Update Rust Query Port
Fix frozen flame some text errors

## Checklist for all submissions

* [ ] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [ ] Have you tested and reviewed your changes with confidence that everything works?
* [ ] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

2023-02-03 06:15 UTC, QuintenQVD0 requested changes

2023-02-03 06:15 UTC, QuintenQVD0 commented on game_eggs/steamcmd_servers/rust/rust_autowipe/egg-rust-autowipe.json
> +    "author": "kano@wapriaily.com",
Swapping author is not done

2023-02-03 06:15 UTC, QuintenQVD0 commented on game_eggs/steamcmd_servers/frozen_flame/egg-frozen-flame.json
> +            "description": "The server name",
This was not exported from a panel

2023-02-03 06:17 UTC, QuintenQVD0 commented
Aslo fill in the pr checklist

2023-02-03 06:38 UTC, Wapriaily commented
Changed

2023-02-03 13:12 UTC, parkervcp requested changes

2023-02-03 13:12 UTC, parkervcp commented on game_eggs/steamcmd_servers/frozen_flame/egg-frozen-flame.json
> +    "author": "parker@parkervcp.com",
why did you change the author here?

2023-02-03 14:21 UTC, Wapriaily commented on game_eggs/steamcmd_servers/frozen_flame/egg-frozen-flame.json
> +    "author": "parker@parkervcp.com",
Sorry, I export that's it.

2023-02-04 20:30 UTC, Software-Noob approved these changes
It'd be ideal in the future to have one PR for each egg. LGTM :+1:

2023-02-04 21:01 UTC, parkervcp approved these changes

2023-02-07 07:12 UTC, Wapriaily commented
Can it be merged? @QuintenQVD0

2023-02-07 07:35 UTC, merged