Add Limbo egg
parkervcp/eggs pull request #2128
Opened 2023-02-10 12:11 UTC by xMikux

# Description

Another Limbo from [LOOHP](https://github.com/LOOHP/Limbo).

## Checklist for all submissions

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you tested and reviewed your changes with confidence that everything works?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

## New egg Submissions

1. [x] Does your submission pass tests (server is connectable)?
2. [ ] Does your egg use a custom docker image?
    * [ ] Have you tried to use a generic image?
    * [ ] Did you PR the necessary changes to make it work?
3. [x] Have you added the egg to the main README.md and any other README files in subdirectories of the egg (e.g /game_eggs) according to the alphabetical order?
4. [x] Have you added a unique README.md for the egg you are adding according to the alphabetical order?
5. [x] You verify that the start command applied does not use a shell script
    * [ ] If some script is needed then it is part of a current yolk or a PR to add one
6. [x] The egg was exported from the panel

2023-02-15 14:33 UTC, parkervcp commented
> Another Limbo from [LOOHP](https://github.com/LOOHP/Limbo).

There is already a limbo server. Is there a reason to add another?

2023-02-15 17:08 UTC, xMikux commented
Yes, these two are slightly different.
And I see somewhere that still has someone saying about Limbo eggs, so it will be good to have one.

2023-03-19 12:44 UTC, QuintenQVD0 commented
if  you add it to all needed README.md then this can be merged

2023-03-19 14:35 UTC, xMikux commented
Hi, I updated the missing readme.

2023-03-19 14:36 UTC, QuintenQVD0 requested changes

2023-03-19 14:36 UTC, QuintenQVD0 commented on game_eggs/minecraft/java/limbo/egg-limbo.json
> +            "script": "#!\/bin\/ash\r\n# Limbo Installation Script\r\n#\r\n# Server Files: \/mnt\/server\r\nLATEST_LIMBO_NAME=$(curl -s https:\/\/ci.loohpjames.com\/job\/Limbo\/lastSuccessfulBuild\/a
please also add here the logic to rename to old .jar to a .jar.old for if they hit reinstall + you don't use here the {{SERVER_JARFILE}} variable but hard coded it:

```ash
#!/bin/ash
# Limbo Installation Script
#
# Server Files: /mnt/server
mkdir -p /mnt/server

LATEST_LIMBO_NAME=$(curl -s https://ci.loohpjames.com/job/Limbo/lastSuccessfulBuild/api/json | jq -r .artifacts[1].displayPath)

cd /mnt/server

if [ -f ${SERVER_JARFILE} ]; then
	mv ${SERVER_JARFILE} ${SERVER_JARFILE}.old
fi

echo "Downloading Limbo server jar..."
curl -o ${SERVER_JARFILE} https://ci.loohpjames.com/job/Limbo/lastSuccessfulBuild/artifact/target/$LATEST_LIMBO_NAME


if [ ! -f server.properties ]; then
    echo -e "Downloading Limbo server.properties"
    curl -o server.properties https://raw.githubusercontent.com/LOOHP/Limbo/master/src/main/resources/server.properties
fi
```

2023-03-19 14:36 UTC, QuintenQVD0 commented on game_eggs/minecraft/java/limbo/egg-limbo.json
> +    "startup": "java -Xms128M -Xmx{{SERVER_MEMORY}}M -jar {{SERVER_JARFILE}}",
Please use here: `java -Xms128M -XX:MaxRAMPercentage=95.0  -jar {{SERVER_JARFILE}}

2023-03-20 19:27 UTC, xMikux commented
I updated the requested changes script and startup command.

2023-03-20 20:08 UTC, QuintenQVD0 commented
> 

It still hardlocks the download .jar name

2023-03-20 20:59 UTC, xMikux commented
Fixed

2023-03-21 05:27 UTC, QuintenQVD0 approved these changes

2023-03-21 05:27 UTC, QuintenQVD0 commented
LGTM!

2023-03-21 05:28 UTC, merged