fix: add ServerDisabledNetworkProtocols in env variables to let user …
parkervcp/eggs pull request #2143
Opened 2023-02-18 19:50 UTC by Tzanou123

# Description

add ServerDisabledNetworkProtocols in env variables to let user manage it if needed!
In my case i was launch egg behind a nat and the param `-ServerDisabledNetworkProtocols ` net to be set to an empty string for letting players connecting on server with your plublic ip  

## Checklist for all submissions

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you tested and reviewed your changes with confidence that everything works?
* [x] Did you branch your changes and PR from that branch and not from your master branch?

* [x] You verify that the start command applied does not use a shell script
  * [ ] If some script is needed then it is part of a current yolk or a PR to add one
* [x] The egg was exported from the panel

2023-02-18 19:51 UTC, Tzanou123 commented
My issue for this problem was : https://github.com/parkervcp/eggs/issues/2141

2023-02-18 20:13 UTC, QuintenQVD0 commented
This was not exported from a panel. If it is then replace the whole egg.

2023-02-18 20:14 UTC, Tzanou123 commented
> This was not exported from a panel. If it is then replace the whole egg.

I just did ;)

2023-02-18 20:34 UTC, QuintenQVD0 commented
It looks fine for me. I have to verify it works  c

2023-02-19 08:34 UTC, Tzanou123 commented
Let me know if you need any help to reproduce the issue.

2023-02-19 11:07 UTC, QuintenQVD0 requested changes

2023-02-19 11:07 UTC, QuintenQVD0 commented on game_eggs/steamcmd_servers/7_days_to_die/egg-7-days-to-die.json
> +            "default_value": "SteamNetworking",
Please make this default value nothing and make it nullable. The host will have to set it.
Check if this parameter is empty and the flag added to the startup that the server still starts

2023-02-20 01:35 UTC, Tzanou123 commented
Done !
Tested it worked !

2023-02-21 15:48 UTC, QuintenQVD0 approved these changes

2023-02-21 15:48 UTC, merged