add Folia
parkervcp/eggs pull request #2345
Opened 2023-07-04 00:24 UTC by Panda260

# Description

I added the Folia project from PaperMC

## Checklist for all submissions

* [X] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [X] Have you tested and reviewed your changes with confidence that everything works?
* [X] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

## New egg Submissions

1. [X] Does your submission pass tests (server is connectable)?
2. [ ] Does your egg use a custom docker image?
    * [ ] Have you tried to use a generic image?
    * [ ] Did you PR the necessary changes to make it work?
3. [X] Have you added the egg to the main README.md and any other README files in subdirectories of the egg (e.g /game_eggs) according to the alphabetical order?
4. [X] Have you added a unique README.md for the egg you are adding according to the alphabetical order?
5. [X] You verify that the start command applied does not use a shell script
    * [ ] If some script is needed then it is part of a current yolk or a PR to add one
6. [X] The egg was exported from the panel

2023-07-04 00:27 UTC, Suqatri approved these changes

2023-07-04 06:23 UTC, QuintenQVD0 commented
This egg is made or exported in a old version of the panel. Update the panel then export. Alsonudr the new 95% startup flag for´max ram for java

2023-07-04 15:55 UTC, Panda260 commented
> This egg is made or exported in a old version of the panel. Update the panel then export. Alsonudr the new 95% startup flag for´max ram for java

My panel in on the Latest version!
https://img.neverstopgaming.net/Panda/chrome_gGdSDmBIPm.png

2023-07-04 15:56 UTC, Panda260 commented
what did you mean with? "Alsonudr the new 95% startup flag for´max ram for java"

2023-07-04 16:02 UTC, Panda260 commented
you mean -XX:MaxRAMPercentage=95.0 ?

2023-07-04 16:06 UTC, QuintenQVD0 commented
> you mean -XX:MaxRAMPercentage=95.0 ?

yea ofc

2023-07-04 16:06 UTC, QuintenQVD0 commented
> > This egg is made or exported in a old version of the panel. Update the panel then export. Alsonudr the new 95% startup flag for´max ram for java
> 
> My panel in on the Latest version! https://img.neverstopgaming.net/Panda/chrome_gGdSDmBIPm.png

your egg export is old as it is still in v1 format so your panel is not up to date but you showed it is up to date so it should export in v2 format

2023-07-04 16:09 UTC, Panda260 commented
> > > This egg is made or exported in a old version of the panel. Update the panel then export. Alsonudr the new 95% startup flag for´max ram for java
> > 
> > 
> > My panel in on the Latest version! https://img.neverstopgaming.net/Panda/chrome_gGdSDmBIPm.png
> 
> your egg export is old as it is still in v1 format so your panel is not up to date but you showed it is up to date so it should export in v2 format

maybe because it is a copy of the Paper egg

2023-07-04 18:38 UTC, QuintenQVD0 commented
No certanly not! The v2 file is compeltly difrend. Just updatr your panel. And you can not directly edit the json file.

2023-07-04 18:39 UTC, QuintenQVD0 requested changes

2023-07-04 18:39 UTC, QuintenQVD0 commented on game_eggs/minecraft/java/folia/egg-folia.json
> +    "exported_at": "2023-07-04T01:55:37+02:00",
Import this egg in to a up to date panel and export it again and fully replace it here.

2023-07-04 18:40 UTC, Panda260 commented
> No certanly not! The v2 file is compeltly difrend. Just updatr your panel. And you can not directly edit the json file.

the Panel says that it is up to date as you can see in the screenshot above
I have the version 1.11.3 is it the Latest one?

2023-07-04 19:09 UTC, QuintenQVD0 commented
> > No certanly not! The v2 file is compeltly difrend. Just updatr your panel. And you can not directly edit the json file.
> 
> the Panel says that it is up to date as you can see in the screenshot above I have the version 1.11.3 is it the Latest one?
> 
> https://img.neverstopgaming.net/Panda/chrome_vlXQMZhRIR.png

Now it is fine. Dont you want your own email on it? 
If someone can test this then this is fine for me.

2023-07-04 21:27 UTC, Panda260 commented
e-mail? no, everything is fine i think

2023-07-08 16:55 UTC, Panda260 commented
what do we have to wait for until the PR is accepted?

2023-07-08 17:23 UTC, QuintenQVD0 commented
Anyone external must confirm it is working and can join.

2023-07-08 18:23 UTC, Panda260 commented
ah okey

2023-07-13 12:34 UTC, Suqatri commented
> Anyone external must confirm it is working and can join.
works for me

2023-07-17 21:01 UTC, parkervcp approved these changes
I am approving this due to it being an upgraded version of paper with multi-threading support.

2023-07-17 21:02 UTC, parkervcp requested changes

2023-07-17 21:02 UTC, parkervcp commented on game_eggs/minecraft/java/folia/egg-folia.json
> +    "author": "parker@pterodactyl.io",
I am not the author of this egg.

2023-07-24 07:44 UTC, Panda260 commented on game_eggs/minecraft/java/folia/egg-folia.json
> +    "author": "parker@pterodactyl.io",
updatet

2023-07-24 21:01 UTC, parkervcp approved these changes

2023-07-30 15:24 UTC, QuintenQVD0 approved these changes
LGTM! thank you!

2023-07-30 15:24 UTC, merged