Add BATTALION: Legacy
parkervcp/eggs pull request #2366
Opened 2023-07-12 17:13 UTC by diedyesterdaywashere

# Description

closes #2364 

shout-out to @gOOvER, he helped me with the egg a lot!

## Checklist for all submissions

* [X] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [X] Have you tested and reviewed your changes with confidence that everything works?
* [X] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

## New egg Submissions

1. [X] Does your submission pass tests (server is connectable)?
2. [ ] Does your egg use a custom docker image?
    * [ ] Have you tried to use a generic image?
    * [ ] Did you PR the necessary changes to make it work?
3. [X] Have you added the egg to the main README.md and any other README files in subdirectories of the egg (e.g /game_eggs) according to the alphabetical order?
4. [X] Have you added a unique README.md for the egg you are adding according to the alphabetical order?
5. [X] You verify that the start command applied does not use a shell script
    * [ ] If some script is needed then it is part of a current yolk or a PR to add one
6. [X] The egg was exported from the panel

2023-07-12 17:33 UTC, gOOvER approved these changes
egg works fine. Server is shown in serverlist and you can connect to it

2023-07-13 17:05 UTC, QuintenQVD0 requested changes
Just those 2, everything else is fine

2023-07-13 17:05 UTC, QuintenQVD0 commented on game_eggs/steamcmd_servers/battalion_legacy/egg-b-a-t-t-a-l-i-o-n--legacy.json
> +            "rules": "required|string|max:20",
Makz this use the rule `required|string|in:805140`

2023-07-13 17:05 UTC, QuintenQVD0 commented on game_eggs/steamcmd_servers/battalion_legacy/egg-b-a-t-t-a-l-i-o-n--legacy.json
> +            "name": "Auto Update",
Add a mentione here that it only happens on restart.

2023-07-13 17:16 UTC, diedyesterdaywashere commented
@QuintenQVD0 here you go, added your changes

2023-07-13 17:18 UTC, QuintenQVD0 approved these changes

2023-07-13 17:19 UTC, merged

2023-07-13 17:19 UTC, QuintenQVD0 commented
LGTM! Thank you.