Update egg-team-fortress-2-classic.json
parkervcp/eggs pull request #2367
Opened 2023-07-13 22:20 UTC by TheKing1543

Made it work, lol.

# Description

The egg didn't work so I sorted it out with the help of a Team Fortress 2 Classic developer.

## Checklist for all submissions

* [ ] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [X ] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [X ] Have you tested and reviewed your changes with confidence that everything works?
* [ ] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:
 Because I just forked the repo to fix the TF2C bug.

* [ X] You verify that the start command applied does not use a shell script
  * [ ] If some script is needed then it is part of a current yolk or a PR to add one
* [X] The egg was exported from the panel

2023-07-13 22:23 UTC, parkervcp commented
@TheKing1543 What was the exact change made here?

2023-07-13 22:29 UTC, TheKing1543 commented
The source multiplayer needs a folder named tf2classic to work, that the egg was simply not making, also, the zip format that the tf2c devs use is not unzipable (at least from my server), and it lead to errors unzipping, so they worked up a solution and gave me another link to a zip that is actually usable

2023-07-13 22:35 UTC, TheKing1543 commented
I'll explain further

- When the server installs, there needs to be a "tf2classic" folder inside root to make SourceSDK load TF2 Classic, one of the problem was, that it was expanding the TF2C folder inside root, merging with SteamCMD and messing everything up.

- There was another error, at least with my server, "need pk compat". That was when extracting the zip file. So the developer gave me another link to a zip file that did not require pk compat.

2023-07-14 14:51 UTC, QuintenQVD0 commented
You are not allowed to change the authoe mail! Pleasd change it back.

2023-07-15 01:13 UTC, parkervcp requested changes

2023-07-15 01:13 UTC, parkervcp commented on game_eggs/steamcmd_servers/team_fortress_2_classic/egg-team-fortress-2-classic.json
> -    "author": "eggs@scattergun.io",
This needs to stay the same

2023-07-16 12:42 UTC, parkervcp approved these changes

2023-07-16 12:42 UTC, merged