Added Elixir Egg
parkervcp/eggs pull request #2450
Opened 2023-08-31 11:20 UTC by avoxmr

# Description
Added Elixir Egg.

## Checklist for all submissions

* [X] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [X] Have you tested and reviewed your changes with confidence that everything works?
* [X] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

* [X] You verify that the start command applied does not use a shell script
  * [X] If some script is needed then it is part of a current yolk or a PR to add one
* [X] The egg was exported from the panel

## New egg Submissions

1. [X] Does your submission pass tests (server is connectable)?
2. [X] Does your egg use a custom docker image?
    * [X] Have you tried to use a generic image?
    * [X] Did you PR the necessary changes to make it work?
3. [X] Have you added the egg to the main README.md and any other README files in subdirectories of the egg (e.g /game_eggs) according to the alphabetical order?
4. [X] Have you added a unique README.md for the egg you are adding according to the alphabetical order?
5. [X] You verify that the start command applied does not use a shell script
    * [X] If some script is needed then it is part of a current yolk or a PR to add one
6. [X] The egg was exported from the panel

2023-08-31 11:36 UTC, QuintenQVD0 requested changes

2023-08-31 11:36 UTC, QuintenQVD0 commented on generic/elixir/egg-elixir.json
> +            "container": "debian:buster-slim",
Use bullseye-slim

2023-08-31 12:17 UTC, QuintenQVD0 commented
You can not directly edit the .json file! All changes must be made in a panel, then exported 1nd fully replaced

2023-08-31 12:19 UTC, avoxmr commented
Ah i see, thanks for letting me know.

2023-08-31 12:26 UTC, avoxmr commented
I have replaced the old egg with a new egg that i have exported from the panel.

2023-09-22 18:08 UTC, QuintenQVD0 approved these changes
LGTM!

2023-09-22 18:08 UTC, merged