Added Dont Strave Together Modded Egg
parkervcp/eggs pull request #2657
Opened 2024-01-12 10:19 UTC by KenRen98

# Description

This separate egg is meant to fix a bug caused by original DST egg, the server in co-process wont start if mod added. This egg uses Superivisord to manage multiple processes, which is recommended by Docker official website.

However, there is an imperfection in this egg implementation, due to the bad design of the server software. It wont take any linux standard signal for exiting, only “c_shutdown()”. I have tried many ways to implement a shutdown method to gracefully shutdown both shards of the game, but it seemed the tries are waste of time and might requrie more package to be added. Thus I made a warnning in stead to alert the user to manually shutdown the servers, anyway its a modded server, currently no better way to solve it. But its definitely better to have a broken server-stop, rather than a broken server-start which causes confusion to the user.

( I literally have spent many month to figure out why the cave shard wont start when certain mods added )

## Checklist for all submissions

* [ x ] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [ x ] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [ x ] Have you tested and reviewed your changes with confidence that everything works?
* [ ] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?: will delete this fork after and re fork

## New egg Submissions

1. [ x ] Does your submission pass tests (server is connectable)?
2. [ ] Does your egg use a custom docker image?
    * [ ] Have you tried to use a generic image?
    * [ x ] Did you PR the necessary changes to make it work?
3. [ x ] Have you added the egg to the main README.md and any other README files in subdirectories of the egg (e.g /game_eggs) according to the alphabetical order?
4. [ x ] Have you added a unique README.md for the egg you are adding according to the alphabetical order?
5. [ x ] You verify that the start command applied does not use a shell script
    * [ ] If some script is needed then it is part of a current yolk or a PR to add one
6. [ x ] The egg was exported from the panel

2024-01-12 12:16 UTC, QuintenQVD0 requested changes

2024-01-13 06:05 UTC, KenRen98 commented on game_eggs/steamcmd_servers/dont_starve/modded/egg-don-t-starve-together-modded.json
> +    "startup": "supervisord -c .\/Supervisord\/supervisord.conf & sleep 1 && cat Warnning.txt & sleep 5 && supervisorctl -c .\/Supervisord\/supervisord.conf",
Any better ideas or solution? well, all Im asking is to get modded server to work properly.

2024-01-17 18:48 UTC, KenRen98 commented on game_eggs/steamcmd_servers/dont_starve/modded/egg-don-t-starve-together-modded.json
> +    "startup": "supervisord -c .\/Supervisord\/supervisord.conf & sleep 1 && cat Warnning.txt & sleep 5 && supervisorctl -c .\/Supervisord\/supervisord.conf",
> Not allowed. As this way the startup is user editable.

Can I bulid this into the source image for blocking user editing it.

2024-01-17 20:30 UTC, QuintenQVD0 commented on game_eggs/steamcmd_servers/dont_starve/modded/egg-don-t-starve-together-modded.json
> +    "startup": "supervisord -c .\/Supervisord\/supervisord.conf & sleep 1 && cat Warnning.txt & sleep 5 && supervisorctl -c .\/Supervisord\/supervisord.conf",
> > Not allowed. As this way the startup is user editable.
> 
> Can I bulid this into the source image for blocking user editing it.

Then that would need to be a custom image added to the game registrar

2024-12-23 08:26 UTC, closed without merging