Update `HumanitZ` egg
parkervcp/eggs pull request #2672
Opened 2024-01-20 11:24 UTC by vp-en

# Description

Changes:
- Added a missing variable, `LOOT_RESPAWN`. Apparently missed that in the original commit.
- Added a description for the variable `BUILDING_HEALTH`, now that it has been added to the official docs
- Added two new variables, `ALLOW_DISMANTLE` and `ALLOW_HOUSE_DISMANTLE`

## Checklist for all submissions

* [X] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [X] Have you tested and reviewed your changes with confidence that everything works?
* [X] Did you branch your changes and PR from that branch and not from your master branch?

* [X] You verify that the start command applied does not use a shell script
* [X] The egg was exported from the panel

2024-01-20 11:33 UTC, QuintenQVD0 requested changes

2024-01-20 11:33 UTC, QuintenQVD0 commented on game_eggs/steamcmd_servers/humanitz/egg-humanit-z.json
> +            "rules": "required|numeric",
Set this to boolean validation.

2024-01-20 11:33 UTC, QuintenQVD0 commented on game_eggs/steamcmd_servers/humanitz/egg-humanit-z.json
> +            "field_type": "text"
Same here

2024-01-20 11:33 UTC, QuintenQVD0 commented on game_eggs/steamcmd_servers/humanitz/egg-humanit-z.json
> +            "rules": "required|numeric",
Same

2024-01-20 11:40 UTC, vp-en commented on game_eggs/steamcmd_servers/humanitz/egg-humanit-z.json
> +            "rules": "required|numeric",
Oh yeah, whoops. I'll fix all of them.

2024-01-23 08:20 UTC, QuintenQVD0 approved these changes
LGTM! Thanks

2024-01-23 08:20 UTC, closed without merging