Allow EXILED Modification to run Auto Updater
parkervcp/eggs pull request #777
Opened 2020-11-04 14:26 UTC by Thiritin

I'm proposing this change as it will add an Environment Variable used by the EXILED (a Popular SCP:SL Mods Framework) to run its auto updater. Otherwise, the user could run into an issue with his server not starting.

I know this is normally not used to support modifications. But as this is only an environment variable I will propose the change anyway.

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

### Changes to an existing Egg:

1. [x] Have you added an explanation of what your changes do and why you'd like us to include them?
2. [ ] Have you tested your Egg changes?

2020-11-04 14:29 UTC, Thiritin commented
![image](https://user-images.githubusercontent.com/6755282/98123659-6efcb800-1eb2-11eb-9c9e-92de2d4c7697.png)
Egg Modification works and Customers EXILED Modification does complete. Before it errored with a message that the `DOTNET_BUNDLE_EXTRACT_BASE_DIR` is not set.

2020-11-04 14:33 UTC, Thiritin commented
I also tested a fresh Server Install just to be sure. Succeeds without error (as expected).
![image](https://user-images.githubusercontent.com/6755282/98124109-06620b00-1eb3-11eb-84a6-95bd0cbac28b.png)

2020-11-04 21:44 UTC, parkervcp requested changes
this could be added as a variable where the startup doesn't need to be edited and the end user can't see this.

2020-11-05 00:09 UTC, Thiritin commented on steamcmd_servers/scpsl/dedicated/egg-scpsl.json
> +    "startup": "export DOTNET_BUNDLE_EXTRACT_BASE_DIR=.\/dotnet-bundle && .\/LocalAdmin {{SERVER_PORT}}",
51c8a80

2020-12-05 12:39 UTC, parkervcp approved these changes

2020-12-05 12:39 UTC, merged