Update/altv
parkervcp/eggs pull request #954
Opened 2021-01-28 11:54 UTC by paz

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

### Changes to an existing Egg:

1. [x] Have you added an explanation of what your changes do and why you'd like us to include them?
2. [x] Have you tested your Egg changes?

In summary, this adds nodejs to the image and simplifies the install script to use the updater script mentioned in the installation page on the altV wiki

2021-01-28 12:42 UTC, parkervcp requested changes

2021-01-28 12:42 UTC, parkervcp commented on gta/altv/egg-alt--v.json
> +    "startup": ".\/update.sh && chmod +x .\/altv-server && .\/altv-server",
no scripts in the startup.

2021-01-28 12:42 UTC, parkervcp commented on gta/altv/egg-alt--v.json
> +            "script": "#!\/bin\/bash\r\n# AltV Install Script\r\n#\r\n# Server Files: \/mnt\/server\r\n# BUILD=stable ## this should be an egg variable.\r\napt update && apt install -y libatomic1 zip
I will not accept you pulling another script to run the install. Users can run reinstall in 1.2+ so they can update that way.

2021-01-31 13:29 UTC, paz commented
here, i don't think the script will change much anyway. I hope this is ok

2021-01-31 13:32 UTC, paz commented
oops i forgot to change startup command, hold on

2021-02-11 13:20 UTC, merged